apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver-deployment
  labels:
    app: gatewayserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gatewayserver
  template:
    metadata: 
      labels:
        app: gatewayserver
    spec: 
      containers:
        - name: gatewayserver
          image: miguelmazo/gatewayserver
          ports:
          - containerPort: 8072
          env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: SPRING_PROFILES_ACTIVE
          - name: SPRING_CONFIG_IMPORT
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: SPRING_CONFIG_IMPORT
          - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            valueFrom:
              configMapKeyRef:
                name: configmap
                key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE